### ISSUE TITLE
fails to startup

### ISSUE THREAD

**Issue by 0x-Jayveersinh-Raj** [livekit-examples/outbound-caller-python#22]
$ python agent.py dev                                                                                                                                                                                     
2025-08-12 17:37:15,873 - DEBUG asyncio - Using proactor: IocpProactor 
2025-08-12 17:37:15,880 - DEV  livekit.agents - Watching C:\Users\jayveersinh.raj\Downloads\outbound-caller-python 
2025-08-12 17:37:18,309 - DEBUG asyncio - Using proactor: IocpProactor 
2025-08-12 17:37:18,320 - INFO livekit.agents - starting worker {"version": "1.2.5", "rtc-version": "1.0.12"}
2025-08-12 17:37:18,320 - INFO livekit.agents - starting inference executor 
2025-08-12 17:37:18,334 - INFO livekit.agents - initializing process {"pid": 13700, "inference": true}
2025-08-12 17:37:20,757 - DEBUG livekit.agents - initializing inference runner {"runner": "lk_end_of_utterance_en", "pid": 13700, "inference": true}
2025-08-12 17:37:28,338 - INFO livekit.agents - killing process {"pid": 13700, "inference": true}
2025-08-12 17:37:28,339 - ERROR livekit.agents - worker failed 
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\ipc\channel.py", line 47, in arecv_message
    return _read_message(await dplx.recv_bytes(), messages)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\utils\aio\duplex_unix.py", line 35, in recv_bytes
    len_bytes = await self._reader.readexactly(4)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\asyncio\streams.py", line 769, in readexactly
    await self._wait_for_data('readexactly')
  File "C:\Python313\Lib\asyncio\streams.py", line 539, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\cli\_run.py", line 79, in _worker_run
    await worker.run()
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\worker.py", line 402, in run
    await self._inference_executor.initialize()
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\ipc\supervised_proc.py", line 169, in initialize
    init_res = await asyncio.wait_for(
               ^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "C:\Python313\Lib\asyncio\tasks.py", line 506, in wait_for
    async with timeouts.timeout(timeout):
               ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python313\Lib\asyncio\timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
2025-08-12 17:37:28,349 - ERROR livekit.agents - Error in _read_ipc_task 
Traceback (most recent call last):
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\utils\aio\duplex_unix.py", line 35, in recv_bytes
    len_bytes = await self._reader.readexactly(4)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\asyncio\streams.py", line 767, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 4 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\utils\log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\cli\watcher.py", line 120, in _read_ipc_task
    msg = await channel.arecv_message(self._pch, proto.IPC_MESSAGES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\ipc\channel.py", line 47, in arecv_message
    return _read_message(await dplx.recv_bytes(), messages)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayveersinh.raj\Downloads\outbound-caller-python\venv\Lib\site-packages\livekit\agents\utils\aio\duplex_unix.py", line 43, in recv_bytes
    raise DuplexClosed() from e
livekit.agents.utils.aio.duplex_unix.DuplexClosed

**Comment by Milindk1** [comment]
This problem is most likely due to your VAD (voice auto detector) not being initialised or loaded well, as the code stops after EOU gets triggered. Can you share your AgentSession code? 
For me Silero Voice Activity Detector works perfectly.

**Comment by 0x-Jayveersinh-Raj** [comment]
I was using a free version of livekit most likely that was the issue, as it was fixed for many by just having a paid account. However, it's worth noting that it did work for a while, then after 2-3 tries, it started throwing this error.

**Comment by Milindk1** [comment]
I'm on the build plan as well. You just need to find a good VAD that works with your environment. Is the problem still persisting?

**Comment by 0x-Jayveersinh-Raj** [comment]
Ah, I see. But actually eventually I figured out another open source solution to it, it's called bolna. Required a few fixes that I fixed. The only problem with livekit is the extra dependency, however, got to admit, go rooms in livekit a little faster, from a few milliseconds to a second.
